In [1]:
import pandas as pd

In [11]:
data = pd.read_excel("data/base_dados_pede_2024.xlsx")
data.head()

,RA,Fase,Turma,Nome,Ano nasc,Idade 22,Gênero,Ano ingresso,Instituição de ensino,Pedra 20,...,Inglês,Indicado,Atingiu PV,IPV,IAN,Fase ideal,Defas,Destaque IEG,Destaque IDA,Destaque IPV
0,RA-1,7,A,Aluno-1,2003,19,Menina,2016,Escola Pública,Ametista,...,6.0,Sim,Não,7.278,5.0,Fase 8 (Universitários),-1,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...
1,RA-2,7,A,Aluno-2,2005,17,Menina,2017,Rede Decisão,Ametista,...,9.7,Não,Não,6.778,10.0,Fase 7 (3º EM),0,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...
2,RA-3,7,A,Aluno-3,2005,17,Menina,2016,Rede Decisão,Ametista,...,6.9,Não,Não,7.556,10.0,Fase 7 (3º EM),0,Destaque: A sua boa entrega das lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Destaque: A sua boa integração aos Princípios ...
3,RA-4,7,A,Aluno-4,2005,17,Menino,2017,Rede Decisão,Ametista,...,8.7,Não,Não,5.278,10.0,Fase 7 (3º EM),0,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...
4,RA-5,7,A,Aluno-5,2005,17,Menina,2016,Rede Decisão,Ametista,...,5.7,Não,Não,7.389,10.0,Fase 7 (3º EM),0,Destaque: A sua boa entrega das lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...

In [13]:
data.shape

(860, 42)

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     860 non-null    object
 1   Fase                   860 non-null    int64
 2   Turma                  860 non-null    object
 3   Nome                   860 non-null    object
 4   Ano nasc               860 non-null    int64
 5   Idade 22               860 non-null    int64
 6   Gênero                 860 non-null    object
 7   Ano ingresso           860 non-null    int64
 8   Instituição de ensino  860 non-null    object
 9   Pedra 20               323 non-null    object
 10  Pedra 21               462 non-null    object
 11  Pedra 22               860 non-null    object
 12  INDE 22                860 non-null    float64
 13  Cg                     860 non-null    int64
 14  Cf                     860 non-null    int64
 15  Ct                     860 non-null    int64
 16  Nº Av                  860 non-null    int64
 17  Avaliador1             860 non-null    object
 18  Rec Av1                860 non-null    object
 19  Avaliador2             860 non-null    object
 20  Rec Av2                860 non-null    object
 21  Avaliador3             534 non-null    object
 22  Rec Av3                860 non-null    object
 23  Avaliador4             310 non-null    object
 24  Rec Av4                296 non-null    object
 25  IAA                    860 non-null    float64
 26  IEG                    860 non-null    float64
 27  IPS                    860 non-null    float64
 28  Rec Psicologia         860 non-null    object
 29  IDA                    860 non-null    float64
 30  Matem                  858 non-null    float64
 31  Portug                 858 non-null    float64
 32  Inglês                 283 non-null    float64
 33  Indicado               860 non-null    object
 34  Atingiu PV             860 non-null    object
 35  IPV                    860 non-null    float64
 36  IAN                    860 non-null    float64
 37  Fase ideal             860 non-null    object
 38  Defas                  860 non-null    int64
 39  Destaque IEG           860 non-null    object
 40  Destaque IDA           860 non-null    object
 41  Destaque IPV           860 non-null    object
dtypes: float64(10), int64(9), object(23)
memory usage: 282.3+ KB

In [20]:
rename_columns = {
    "Ano nasc": "Ano de Nascimento do Aluno",
    "Idade 22": "Idade do Aluno",
    "Ano ingresso": "Ano de Ingresso na Passos Mágicos",
    "INDE 22": "Índice de Desenvolvimento Educacional (INDE)",
    "Cg": "Classificação Geral (Ranking Geral)",
    "Cf": "Classificação na Fase (Ranking por Fase)",
    "Ct": "Classificação na Turma (Ranking por Turma)",
    "Pedra 20": "Pedra 2020",
    "Pedra 21": "Pedra 2021",
    "Pedra 22": "Pedra 2022",
    "Nº Av": "Quantidade de Avaliações",
    "Avaliador1": "Equipe Avaliadora 1",
    "Rec Av1": "Recomendação da Equipe Avaliadora 1",
    "Avaliador2": "Equipe Avaliadora 2",
    "Rec Av2": "Recomendação da Equipe Avaliadora 2",
    "Avaliador3": "Equipe Avaliadora 3",
    "Rec Av3": "Recomendação da Equipe Avaliadora 3",
    "Avaliador4": "Equipe Avaliadora 4",
    "Rec Av4": "Recomendação da Equipe Avaliadora 4",
    "IAA": "Indicador de Autoavaliação",
    "IEG": "Indicador de Engajamento",
    "IPS": "Indicador Psicossocial",
    "Rec Psicologia": "Recomendação da Equipe de Psicologia",
    "IDA": "Indicador de Aprendizagem",
    "Matem": "Nota Média de Matemática",
    "Portug": "Nota Média de Português",
    "Inglês": "Nota Média de Inglês",
    "Indicado": "Indicado para Bolsa",
    "Atingiu PV": "Atingiu Ponto de Virada",
    "IPV": "Indicador de Ponto de Virada",
    "IAN": "Indicador de Adequação ao Nível",
    "Defas": "Nível de Defasagem",
    "Destaque IEG": "Observações sobre Indicador de Engajamento",
    "Destaque IDA": "Observações sobre Indicador de Aprendizagem",
    "Destaque IPV": "Observações sobre Indicador de Ponto de Virada"
}

In [22]:
pd.set_option('display.max_columns', None)
df = data.rename(columns=rename_columns)
df.head()

,RA,Fase,Turma,Nome,Ano de Nascimento do Aluno,Idade do Aluno,Gênero,Ano de Ingresso na Passos Mágicos,Instituição de ensino,Pedra 2020,Pedra 2021,Pedra 2022,Índice de Desenvolvimento Educacional (INDE),Classificação Geral (Ranking Geral),Classificação na Fase (Ranking por Fase),Classificação na Turma (Ranking por Turma),Quantidade de Avaliações,Equipe Avaliadora 1,Recomendação da Equipe Avaliadora 1,Equipe Avaliadora 2,Recomendação da Equipe Avaliadora 2,Equipe Avaliadora 3,Recomendação da Equipe Avaliadora 3,Equipe Avaliadora 4,Recomendação da Equipe Avaliadora 4,Indicador de Autoavaliação,Indicador de Engajamento,Indicador Psicossocial,Recomendação da Equipe de Psicologia,Indicador de Aprendizagem,Nota Média de Matemática,Nota Média de Português,Nota Média de Inglês,Indicado para Bolsa,Atingiu Ponto de Virada,Indicador de Ponto de Virada,Indicador de Adequação ao Nível,Fase ideal,Nível de Defasagem,Observações sobre Indicador de Engajamento,Observações sobre Indicador de Aprendizagem,Observações sobre Indicador de Ponto de Virada
0,RA-1,7,A,Aluno-1,2003,19,Menina,2016,Escola Pública,Ametista,Ametista,Quartzo,5.783,753,18,10,4,Avaliador-5,Mantido na Fase atual,Avaliador-27,Promovido de Fase + Bolsa,Avaliador-28,Promovido de Fase,Avaliador-31,Mantido na Fase atual,8.3,4.1,5.6,Requer avaliação,4.0,2.7,3.5,6.0,Sim,Não,7.278,5.0,Fase 8 (Universitários),-1,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...
1,RA-2,7,A,Aluno-2,2005,17,Menina,2017,Rede Decisão,Ametista,Ametista,Ametista,7.055,469,8,3,4,Avaliador-5,Promovido de Fase,Avaliador-27,Promovido de Fase + Bolsa,Avaliador-28,Promovido de Fase,Avaliador-31,Promovido de Fase + Bolsa,8.8,5.2,6.3,Sem limitações,6.8,6.3,4.5,9.7,Não,Não,6.778,10.0,Fase 7 (3º EM),0,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...
2,RA-3,7,A,Aluno-3,2005,17,Menina,2016,Rede Decisão,Ametista,Ametista,Ágata,6.591,629,13,6,4,Avaliador-5,Promovido de Fase,Avaliador-27,Promovido de Fase + Bolsa,Avaliador-28,Promovido de Fase + Bolsa,Avaliador-31,Promovido de Fase + Bolsa,0.0,7.9,5.6,Sem limitações,5.6,5.8,4.0,6.9,Não,Não,7.556,10.0,Fase 7 (3º EM),0,Destaque: A sua boa entrega das lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Destaque: A sua boa integração aos Princípios ...
3,RA-4,7,A,Aluno-4,2005,17,Menino,2017,Rede Decisão,Ametista,Ametista,Quartzo,5.951,731,15,7,4,Avaliador-5,Promovido de Fase,Avaliador-27,Mantido na Fase atual,Avaliador-28,Mantido na Fase atual,Avaliador-31,Mantido na Fase atual,8.8,4.5,5.6,Requer avaliação,5.0,2.8,3.5,8.7,Não,Não,5.278,10.0,Fase 7 (3º EM),0,Melhorar: Melhorar a sua entrega de lições de ...,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...
4,RA-5,7,A,Aluno-5,2005,17,Menina,2016,Rede Decisão,Ametista,Ametista,Ametista,7.427,344,6,2,4,Avaliador-5,Promovido de Fase,Avaliador-27,Promovido de Fase + Bolsa,Avaliador-28,Promovido de Fase + Bolsa,Avaliador-31,Promovido de Fase + Bolsa,7.9,8.6,5.6,Requer avaliação,5.2,7.0,2.9,5.7,Não,Não,7.389,10.0,Fase 7 (3º EM),0,Destaque: A sua boa entrega das lições de casa.,Melhorar: Empenhar-se mais nas aulas e avaliaç...,Melhorar: Integrar-se mais aos Princípios Pass...

In [ ]:
df.drop(columns=["Nome"],inplace=True)

In [23]:
df.to_csv("base_dados_pede_2024_ajustado.csv", index=False)